### ISSUE TITLE
Create component => src/components/ProjectCard.tsx

### ISSUE THREAD

**Issue by kleneway** [PioneerSquareLabs/otto-playground#309]
Create a React component for src/components/ProjectCard.tsx. Here are the instructions:

### Description
We need to create a new React component called `ProjectCard.tsx` that will be responsible for displaying project information in a card format. This component will be used on the dashboard page to show a list of projects the user is working on. The component should be written in TypeScript using ES6 syntax, such as arrow functions.

### Props
The `ProjectCard` component should accept the following props:

```typescript
interface ProjectCardProps {
  project: Project;
}
```

The `project` prop is an object that adheres to the `Project` interface from the `types.ts` file.

### Imports
The following imports will be needed for this component:

```typescript
import React from 'react';
import { Project } from '~/types';
import '~/styles/globals.css';
```

### Component Structure
The `ProjectCard` component should be a functional component that takes the `ProjectCardProps` as its props. The component should display the project's name, description, and a link to the project page. The link should navigate the user to the project page with the project's ID as a URL parameter (e.g., `/project/1`).

### State Management
There is no need for state management in this component, as it only displays the information passed through its props.

### Rendering
The component should render a card with the following structure:

1. A heading with the project's name
2. A paragraph with the project's description (if available)
3. A link to the project page

The card should have a consistent style with other cards in the application, using the Tailwind CSS classes.

### User Interaction
When the user clicks on the link to the project page, they should be navigated to the corresponding project page with the project's ID as a URL parameter.

### Example
Here's an example of how the `ProjectCard` component should be structured:

```typescript
import React from 'react';
import { Project } from '~/types';
import '~/styles/globals.css';

interface ProjectCardProps {
  project: Project;
}

const ProjectCard: React.FC<ProjectCardProps> = ({ project }) => {
  const { id, name, description } = project;

  return (
    <div className="bg-white shadow-md rounded-md p-4">
      <h3 className="text-xl font-semibold">{name}</h3>
      {description && <p className="text-gray-600 mt-2">{description}</p>}
      <a href={`/project/${id}`} className="text-blue-600 hover:text-blue-800 mt-4 inline-block">
        View Project
      </a>
    </div>
  );
};

export default ProjectCard;
```

### Tasks
- [ ] Create a new `ProjectCard.tsx` file in the `src/components` directory
- [ ] Import the necessary dependencies and styles
- [ ] Define the `ProjectCardProps` interface
- [ ] Create the `ProjectCard` functional component with the specified structure and props
- [ ] Implement the rendering logic for the project's name, description, and link
- [ ] Test the component by using it on the dashboard page with sample project data

Please submit a pull request once the component is complete and tested. If you have any questions or need further clarification, feel free to reach out.
